enum {
    RESULT_OK = 0,
    RESULT_BAD_ARG,
    RESULT_BAD_FILE_TYPE,
    RESULT_OPEN_FAILED, 
    RESULT_BAD_READ,
    RESULT_BAD_WRITE,
    RESULT_BAD_CLOSE,
    RESULT_BAD_FILE_DELETE,
    RESULT_BAD_COPY_TIME,
    RESULT_BAD_READLINK,
    RESULT_BAD_LINK_COPY,
    RESULT_ERR
};

